version: '3.4'

volumes:
  nextcloud:
  
services:
  db:
    image: mariadb:10.4.28
    restart: always
    command: --transaction-isolation=READ-COMMITTED --disable_log_bin
    volumes:
      - /nextcloud/mariadb:/var/lib/mysql

  app:
    build: .
    pull_policy: build
    image: nextcloud:28.0.1-fpm-smb
    restart: always
    links:
      - db
    environment:
      - SMTP_HOST=smtp.pinter-net.at
      - SMTP_SECURE=tls
      - SMTP_AUTHTYPE=LOGIN
      - SMTP_NAME=nextcloud@pinter-net.at
      - SMTP_PORT=587
      - SMTP_PASSWORD=${MAILPW}
      - MAIL_FROM_ADDRESS=nextcloud
      - MAIL_DOMAIN=pinter-net.at
      - PHP_MEMORY_LIMIT=6144M
      - PHP_UPLOAD_LIMIT=8192M
    command: >-
      sh -c '
        {
          echo pm=dynamic;
          echo pm.max_children=220;
          echo pm.start_servers=12;
          echo pm.min_spare_servers=6;
          echo pm.max_spare_servers=18;
        } >> /usr/local/etc/php-fpm.d/www.conf;
        exec /entrypoint.sh php-fpm
      '
    volumes:
      - nextcloud:/var/www/html:z
      - /nextcloud/data:/var/www/html/data
      - /nextcloud/config:/var/www/html/config
      - /nextcloud/custom_apps:/var/www/html/custom_apps
 
  cron:
    build: .
    pull_policy: build
    image: nextcloud:28.0.1-fpm-smb
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
      - /nextcloud/data:/var/www/html/data
      - /nextcloud/config:/var/www/html/config
      - /nextcloud/custom_apps:/var/www/html/custom_apps
    entrypoint: /cron.sh
    depends_on:
      - db

  web:
    image: nginx
    restart: always
    ports:
      - 8080:80
    links:
      - app
    volumes:
      - /nextcloud/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
