version: '3.4'

volumes:
  nextcloud:
  
services:
  db:
    image: mariadb:10.3.38
    restart: always
    command: --transaction-isolation=READ-COMMITTED --disable_log_bin
    volumes:
      - /nextcloud/mariadb:/var/lib/mysql

  app:
    build: .
    pull_policy: build
    image: nextcloud:25.0.6-fpm-smb
    restart: always
    links:
      - db
    volumes:
      - nextcloud:/var/www/html:z
      - /nextcloud/data:/var/www/html/data
      - /nextcloud/config:/var/www/html/config
      - /nextcloud/custom_apps:/var/www/html/custom_apps
 
  cron:
    build: .
    pull_policy: build
    image: nextcloud:25.0.6-fpm-smb
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
      - /nextcloud/data:/var/www/html/data
      - /nextcloud/config:/var/www/html/config
      - /nextcloud/custom_apps:/var/www/html/custom_apps
    entrypoint: /cron.sh
    depends_on:
      - db


  web:
    image: nginx
    restart: always
    ports:
      - 8080:80
    links:
      - app
    volumes:
      - /nextcloud/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
